java/org/mozilla/fenix/tabstray/inactivetabs/InactiveTabs.kt:280:                url = "www.google.com",
google.sh:1:java/org/mozilla/fenix/tabstray/inactivetabs/InactiveTabs.kt:280:                url = "www.google.com",
google.sh:2:res/values-iw/strings.xml:1884:    <string name="search_add_custom_engine_search_string_example" formatted="false">יש להחליף את השאילתה עם ״%s״. לדוגמה:\nhttps://www.google.com/search?q=%s</string>
google.sh:3:res/values-nn-rNO/strings.xml:1927:    <string name="search_add_custom_engine_search_string_example" formatted="false">Byt ut spørjinga med «%s». Eksempel:\nhttps://www.google.com/search?q=%s</string>
google.sh:4:res/values-pt-rBR/strings.xml:1965:    <string name="search_add_custom_engine_search_string_example" formatted="false">Substitua a consulta por “%s”. Por exemplo:\nhttps://www.google.com/search?q=%s</string>
google.sh:5:res/values-my/strings.xml:1332:    <string name="search_add_custom_engine_search_string_example" formatted="false">စုံစမ်းမှုကို “%s” ဖြင့်အစားထိုးပါ။ ဥပမာ။ \n https://www.google.com/search?q= %s</string>
google.sh:6:res/values-gl/strings.xml:1936:    <string name="search_add_custom_engine_search_string_example" formatted="false">Substitúír a consulta por «%s». Exemplo:\nhttps://www.google.com/search?q=%s</string>
google.sh:7:res/values-fr/strings.xml:1983:    <string name="search_add_custom_engine_search_string_example" formatted="false">Remplacer les termes de la recherche par « %s ». Par exemple :\nhttps://www.google.com/search?q=%s</string>
google.sh:8:res/values-dsb/strings.xml:1956:    <string name="search_add_custom_engine_search_string_example" formatted="false">Napšašowanje z „%s“ wuměniś. Pśikład: \nhttps://www.google.com/search?q=%s</string>
google.sh:9:res/values-de/strings.xml:1990:    <string name="search_add_custom_engine_search_string_example" formatted="false">Anfrage durch „%s“ ersetzen. Beispiel:\nhttps://www.google.com/search?q=%s</string>
google.sh:10:res/values-lo/strings.xml:1933:    <string name="search_add_custom_engine_search_string_example" formatted="false">ແທນທີ່ຄິວລີດ້ວຍ “%s”. ຕົວຢ່າ: \nhttps://www.google.com/search?q=%s</string>
google.sh:11:res/values-sat/strings.xml:1926:    <string name="search_add_custom_engine_search_string_example" formatted="false">“%s” ᱥᱟᱞᱟᱜ ᱠᱣᱮᱨᱭ ᱵᱚᱫᱚᱞ ᱢᱮ ᱾ ᱡᱮᱢᱚᱱ:\nhttps://www.google.com/search?q=%s</string>
google.sh:12:res/values-tl/strings.xml:1566:    <string name="search_add_custom_engine_search_string_example" formatted="false">Palitan ang query ng “%s”. Halimbawa:\nhttps://www.google.com/search?q=%s</string>
google.sh:13:res/values-sr/strings.xml:1889:    <string name="search_add_custom_engine_search_string_example" formatted="false">Замените упит са “%s”. Пример:\nhttps://www.google.com/search?q=%s</string>
google.sh:14:res/values-fi/strings.xml:1976:    <string name="search_add_custom_engine_search_string_example" formatted="false">Korvaa kysely käyttäen ”%s”. Esimerkki:\nhttps://www.google.com/search?q=%s</string>
google.sh:15:res/values-vec/strings.xml:822:    <string name="search_add_custom_engine_search_string_example" formatted="false">Sostituire ƚa ciave de reserca co “%s”. Exempio:\nhttps://www.google.com/search?q=%s</string>
google.sh:16:res/values-hr/strings.xml:1951:    <string name="search_add_custom_engine_search_string_example" formatted="false">Zamijeni upit s „%s”. Primjer:\nhttps://www.google.com/search?q=%s</string>
google.sh:17:res/values-es/strings.xml:1978:    <string name="search_add_custom_engine_search_string_example" formatted="false">Reemplazar la consulta con “%s”. Ejemplo:\n https://www.google.com/search?q=%s</string>
google.sh:18:res/values-sc/strings.xml:1561:    <string name="search_add_custom_engine_search_string_example" formatted="false">Sostitui sa chirca cun «%s». Esempru: \nhttps://www.google.com/search?q=%s</string>
google.sh:19:res/values-fur/strings.xml:1955:    <string name="search_add_custom_engine_search_string_example" formatted="false">Sostituìs il test de ricercje cun “%s”. Esempli:\nhttps://www.google.com/search?q=%s</string>
google.sh:20:res/values-tt/strings.xml:1481:    <string name="search_add_custom_engine_search_string_example" formatted="false">Сорауны “%s” юлы белән алыштырыгыз. Мисал өчен:\nhttps://www.google.com/search?q=%s</string>
google.sh:21:res/values-gd/strings.xml:1892:    <string name="search_add_custom_engine_search_string_example" formatted="false">Cuir “%s” an àite na ceist. Ball-eisimpleir:\nhttps://www.google.com/search?q=%s</string>
google.sh:22:res/values-ru/strings.xml:1984:    <string name="search_add_custom_engine_search_string_example" formatted="false">Замените строку запроса на «%s». Пример:\nhttps://www.google.com/search?q=%s</string>
google.sh:23:res/values-kk/strings.xml:1956:    <string name="search_add_custom_engine_search_string_example" formatted="false">Сұранымды &quot;%s&quot; жолымен алмастырыңыз. Мысалы:\nhttps://www.google.com/search?q=%s</string>
google.sh:24:res/values-te/strings.xml:1403:    <string name="search_add_custom_engine_search_string_example" formatted="false">వెతుకుడు పదాన్ని “%s”తో పూరించండి. ఉదాహరణ:\nhttps://www.google.com/search?q=%s</string>
google.sh:25:res/values-ug/strings.xml:1855:    <string name="search_add_custom_engine_search_string_example" formatted="false">سۈرۈشتۈرۈشنى «%s» غا ئالماشتۇرىدۇ. مەسىلەن:\nhttps://www.google.com/search?q=%s</string>
google.sh:26:res/values-ml/strings.xml:1316:    <string name="search_add_custom_engine_search_string_example" formatted="false">അന്വേഷണ വാചകത്തിന് പകരം “%s” എന്നത് ഉപയോഗിക്കുക. ഉദാഹരണം: \nhttps://www.google.com/search?q=%s</string>
google.sh:27:res/values-hi-rIN/strings.xml:1383:    <string formatted="false" name="search_add_custom_engine_search_string_example">“%s” से प्रश्न बदले। उदाहरण:\nhttps://www.google.com/search?q=%s</string>
google.sh:28:res/values-cak/strings.xml:1787:Achi\'el: \nhttps://www.google.com/search?q=%s</string>
google.sh:29:res/values-yo/strings.xml:1694:    <string formatted="false" name="search_add_custom_engine_search_string_example">Rọ́pò ìbéérè pẹ̀lú “%s”. Àpẹẹrẹ:\nhttps://www.google.com/search?q=%s</string>
google.sh:30:res/values-cy/strings.xml:1950:    <string name="search_add_custom_engine_search_string_example" formatted="false">Disodli’r ymholiad â “%s”. Enghraifft:\nhttps://www.google.com/search?q=%s</string>
google.sh:31:res/values-pt-rPT/strings.xml:1962:    <string name="search_add_custom_engine_search_string_example" formatted="false">Substitua a consulta por “%s”. Exemplo: \nhttps://www.google.com/search?q=%s</string>
google.sh:32:res/values-en-rGB/strings.xml:1946:    <string name="search_add_custom_engine_search_string_example" formatted="false">Replace query with “%s”. Example:\nhttps://www.google.com/search?q=%s</string>
google.sh:33:res/values-kaa/strings.xml:1825:    <string name="search_add_custom_engine_search_string_example" formatted="false">Sorawdı “%s” menen almastırıń. Mısalı:\nhttps://www.google.com/search?q=%s</string>
google.sh:34:res/values-ka/strings.xml:1955:    <string name="search_add_custom_engine_search_string_example" formatted="false">მიუთითეთ „%s“ საძიებო ტექსტად. მაგალითი:\nhttps://www.google.com/search?q=%s</string>
google.sh:35:res/values-es-rAR/strings.xml:1980:    <string name="search_add_custom_engine_search_string_example" formatted="false">Reemplazar la consulta con &quot;%s&quot;. Ejemplo:\n https://www.google.com/search?q=%s</string>
google.sh:36:res/values-bg/strings.xml:1453:    <string name="search_add_custom_engine_search_string_example" formatted="false">Заменете заявката с „%s“. Пример:\nhttps://www.google.com/search?q=%s</string>
google.sh:37:res/values-nb-rNO/strings.xml:1930:    <string name="search_add_custom_engine_search_string_example" formatted="false">Bytt ut spørringen med «%s». Eksempel:\nhttps://www.google.com/search?q=%s</string>
google.sh:38:res/values-zh-rCN/strings.xml:1995:    <string name="search_add_custom_engine_search_string_example" formatted="false">用“%s”替换查询关键字。示例：\nhttps://www.google.com/search?q=%s</string>
google.sh:39:res/values-el/strings.xml:1977:    <string name="search_add_custom_engine_search_string_example" formatted="false">Αντικαταστήστε τον όρο αναζήτησης με «%s». Παράδειγμα:\nhttps://www.google.com/search?q=%s</string>
google.sh:40:res/values/strings.xml:1933:    <string name="search_add_custom_engine_search_string_example" formatted="false">Replace query with “%s”. Example:\nhttps://www.google.com/search?q=%s</string>
google.sh:41:res/values-ca/strings.xml:1967:    <string name="search_add_custom_engine_search_string_example" formatted="false">Substituïu la consulta per «%s». Per exemple:\nhttps://www.google.com/search?q=%s</string>
google.sh:42:res/values-be/strings.xml:1981:    <string name="search_add_custom_engine_search_string_example" formatted="false">Змяніць запыт на “%s”. Прыклад:\nhttps://www.google.com/search?q=%s</string>
google.sh:43:res/values-eu/strings.xml:1954:    <string name="search_add_custom_engine_search_string_example" formatted="false">Ordezkatu galdera-katea &quot;%s&quot; testuarekin. Adibidez:\nhttps://www.google.com/search?q=%s</string>
google.sh:44:res/values-cs/strings.xml:1976:    <string name="search_add_custom_engine_search_string_example" formatted="false">Dotaz nahraďte „%s“. Příklad: \nhttps://www.google.com/search?q=%s</string>
google.sh:45:res/values-lij/strings.xml:926:    <string name="search_add_custom_engine_search_string_example" formatted="false">Cangia a ciave de riçerca con “%s”. Ezenpio:\nhttps://www.google.com/search?q=%s</string>
google.sh:46:res/values-en-rCA/strings.xml:1949:    <string name="search_add_custom_engine_search_string_example" formatted="false">Replace query with “%s”. Example:\nhttps://www.google.com/search?q=%s</string>
google.sh:47:res/values-et/strings.xml:1576:    <string name="search_add_custom_engine_search_string_example" formatted="false">Päringu asendamiseks kasuta “%s”. Näiteks \nhttps://www.google.com/search?q=%s</string>
google.sh:48:res/values-es-rCL/strings.xml:1952:    <string name="search_add_custom_engine_search_string_example" formatted="false">Reemplazar la consulta con “%s”. Ejemplo:\n https://www.google.com/search?q=%s</string>
google.sh:49:res/values-ko/strings.xml:2008:    <string name="search_add_custom_engine_search_string_example" formatted="false">쿼리를 “%s”로 대체합니다. 예:\nhttps://www.google.com/search?q=%s</string>
google.sh:50:res/values-pa-rIN/strings.xml:1978:    <string name="search_add_custom_engine_search_string_example" formatted="false">“%s” ਨਾਲ ਕਿਊਰੀ ਨੂੰ ਤਬਦੀਲ ਕਰੋ। ਮਿਸਾਲ ਵਜੋਂ:\nhttps://www.google.com/search?q=%s</string>
google.sh:51:res/values-eo/strings.xml:1964:    <string name="search_add_custom_engine_search_string_example" formatted="false">Anstataŭigi la serĉotan tekston per “%s”. Ekzemple:\nhttps://www.google.com/search?q=%s</string>
google.sh:52:res/values-uz/strings.xml:1722:    <string name="search_add_custom_engine_search_string_example" formatted="false">Soʻrovni “%s” bilan almashtiring. Masalan:\nhttps://www.google.com/search?q=%s</string>
google.sh:53:res/values-gu-rIN/strings.xml:1121:    <string name="search_add_custom_engine_search_string_example" formatted="false">ક્વેરીને “%s”થી બદલો. ઉદાહરણ:\n https://www.google.com/search?q=%s</string>
google.sh:54:res/values-sl/strings.xml:1970:    <string name="search_add_custom_engine_search_string_example" formatted="false">Zamenjajte poizvedbo z &quot;%s&quot;. Primer: \nhttps://www.google.com/search?q=%s</string>
google.sh:55:res/values-rm/strings.xml:1957:    <string name="search_add_custom_engine_search_string_example" formatted="false">Remplazzar il term da tschertga cun «%s». Per exempel: \nhttps://www.google.com/search?q=%s</string>
google.sh:56:res/values-hsb/strings.xml:1964:    <string name="search_add_custom_engine_search_string_example" formatted="false">Naprašowanje z „%s“ wuměnić. Přikład: \nhttps://www.google.com/search?q=%s</string>
google.sh:57:res/values-kab/strings.xml:1919:    <string name="search_add_custom_engine_search_string_example" formatted="false">Beddel aḍris n unadi “%s”. Amedya: \nhttps://www.google.com/search?q=%s</string>
google.sh:58:res/values-sq/strings.xml:1940:    <string name="search_add_custom_engine_search_string_example" formatted="false">Zëvendësoni kërkesën me “%s”. Shembull:\nhttps://www.google.com/search?q=%s</string>
google.sh:59:res/values-zh-rTW/strings.xml:1991:    <string name="search_add_custom_engine_search_string_example" formatted="false">用「%s」取代查詢關鍵字。例如:\nhttps://www.google.com/search?q=%s</string>
google.sh:60:res/values-in/strings.xml:1914:    <string name="search_add_custom_engine_search_string_example" formatted="false">Ganti kueir dengan “%s”. Contoh:\nhttps://www.google.com/search?q=%s</string>
google.sh:61:res/values-da/strings.xml:1945:    <string name="search_add_custom_engine_search_string_example" formatted="false">Erstat forespørgslen med “%s”. Eksempel:\nhttps://www.google.com/search?q=%s</string>
google.sh:62:res/values-th/strings.xml:1934:    <string name="search_add_custom_engine_search_string_example" formatted="false">แทนที่คำค้นด้วย “%s” ตัวอย่าง:\nhttps://www.google.com/search?q=%s</string>
google.sh:63:res/values-kmr/strings.xml:1880:    <string name="search_add_custom_engine_search_string_example" formatted="false">Lêpirsînê bi “%s”ê pev biguherîne. Mînak:\nhttps://www.google.com/search?q=%s</string>
google.sh:64:res/values-is/strings.xml:1949:    <string name="search_add_custom_engine_search_string_example" formatted="false">Skipta út fyrirspurninni með “%s”. Dæmi:\nhttps://www.google.com/search?q=%s</string>
google.sh:65:res/values-it/strings.xml:1997:    <string name="search_add_custom_engine_search_string_example" formatted="false">Sostituire la chiave di ricerca con “%s”. Esempio:\nhttps://www.google.com/search?q=%s</string>
google.sh:66:res/values-hy-rAM/strings.xml:1937:    <string name="search_add_custom_engine_search_string_example" formatted="false">Հարցումը փոխարինել “%s”-ով: Օրինակ՝ \nhttps://www.google.com/search?q=%s</string>
google.sh:67:res/values-gn/strings.xml:2000:    <string name="search_add_custom_engine_search_string_example" formatted="false">Emoambue porandu “%s” ndive. Techapyrã:https://www.google.com/search?q=%s</string>
google.sh:68:res/values-vi/strings.xml:1944:    <string name="search_add_custom_engine_search_string_example" formatted="false">Thay thế chuỗi truy vấn thành “%s”. Ví dụ:\nhttps://www.google.com/search?q=%s</string>
google.sh:69:res/values-ar/strings.xml:1397:    <string name="search_add_custom_engine_search_string_example" formatted="false">استبدِل الاستعلام بِ‍ ”%s“. مثال:\nhttps://www.google.com/search?q=%s</string>
google.sh:70:res/values-kn/strings.xml:1251:    <string formatted="false" name="search_add_custom_engine_search_string_example">ಪ್ರಶ್ನೆಯನ್ನು “%s” ನೊಂದಿಗೆ ಬದಲಾಯಿಸಿ. ಉದಾಹರಣೆ: \n https://www.google.com/search?q=%s</string>
google.sh:71:res/values-trs/strings.xml:1968:    <string name="search_add_custom_engine_search_string_example" formatted="false">Nādūnā sa nana\'uî\'t ngà “%s”. dàj rû\':\nhttps://www.google.com/search?q=%s</string>
google.sh:72:res/values-am/strings.xml:1920:    <string name="search_add_custom_engine_search_string_example" formatted="false">ጥያቄውን በ &quot;%s&quot; ይተኩ። ምሳሌ፡- \nhttps://www.google.com/search?q=%s</string>
google.sh:73:res/values-ia/strings.xml:2007:    <string name="search_add_custom_engine_search_string_example" formatted="false">Replaciar le recerca con “%s”. Exemplo:\nhttps://www.google.com/search?q=%s</string>
google.sh:74:res/values-nl/strings.xml:1955:    <string name="search_add_custom_engine_search_string_example" formatted="false">Zoekvraag vervangen door ‘%s’. Bijvoorbeeld: \nhttps://www.google.com/search?q=%s</string>
google.sh:75:res/values-oc/strings.xml:1969:    <string name="search_add_custom_engine_search_string_example" formatted="false">Remplaçar los tèrmes de la recèrca per « %s ». Per exemple :\nhttps://www.google.com/search?q=%s</string>
google.sh:76:res/values-an/strings.xml:1365:    <string formatted="false" name="search_add_custom_engine_search_string_example">Substituyir la consulta con “%s”. Eixemplo:\n https://www.google.com/search?q=%s</string>
google.sh:77:res/values-mr/strings.xml:1298:    <string name="search_add_custom_engine_search_string_example" formatted="false">क्वेरी “%s” ने बदला. उदा: \nhttps://www.google.com/search?q=%s</string>
google.sh:78:res/values-lt/strings.xml:1442:    <string name="search_add_custom_engine_search_string_example" formatted="false">Vietoje užklausos įrašykite „%s“. Pvz.:\nhttps://www.google.com/search?q=%s</string>
google.sh:79:res/values-es-rMX/strings.xml:1877:    <string name="search_add_custom_engine_search_string_example" formatted="false">Reemplazar la consulta con “%s”. Ejemplo:\n https://www.google.com/search?q=%s</string>
google.sh:80:res/values-sv-rSE/strings.xml:1971:    <string name="search_add_custom_engine_search_string_example" formatted="false">Byt ut frågan med “%s”. Exempel:\nhttps://www.google.com/search?q=%s</string>
google.sh:81:res/values-su/strings.xml:1964:    <string name="search_add_custom_engine_search_string_example" formatted="false">Ganti kueri ku “%s”. Conto:\nhttps://www.google.com/search?q=%s</string>
google.sh:82:res/values-ta/strings.xml:1056:    <string name="search_add_custom_engine_search_string_example" formatted="false">வினவலை “%s” ஆக மாற்றுக. எ.கா:\nhttps://www.google.com/search?q=%s</string>
google.sh:83:res/values-ja/strings.xml:1985:    <string name="search_add_custom_engine_search_string_example" formatted="false">クエリーを “%s” に置き換えます。例:\nhttps://www.google.com/search?q=%s</string>
google.sh:84:res/values-es-rES/strings.xml:1992:    <string name="search_add_custom_engine_search_string_example" formatted="false">Reemplazar la consulta con “%s”. Ejemplo:\n https://www.google.com/search?q=%s</string>
google.sh:85:res/values-hu/strings.xml:1954:    <string name="search_add_custom_engine_search_string_example" formatted="false">A keresés cseréje erre: „%s”. Példa:\nhttps://www.google.com/search?q=%s</string>
google.sh:86:res/values-fy-rNL/strings.xml:1941:    <string name="search_add_custom_engine_search_string_example" formatted="false">Sykfraach ferfange troch ‘%s’. Bygelyks: \nhttps://www.google.com/search?q=%s</string>
google.sh:87:res/values-ga-rIE/strings.xml:816:    <string formatted="false" name="search_add_custom_engine_search_string_example">Cuir “%s” in áit an iarratais. Mar shampla:\nhttps://www.google.com/search?q=%s</string>
google.sh:88:res/values-uk/strings.xml:1966:    <string name="search_add_custom_engine_search_string_example" formatted="false">Змініть запит на “%s”. Зразок:\nhttps://www.google.com/search?q=%s</string>
google.sh:89:res/values-skr/strings.xml:1847:مثال:\nhttps://www.google.com/search?q=%s</string>
google.sh:90:res/values-sk/strings.xml:1965:    <string name="search_add_custom_engine_search_string_example" formatted="false">Nahraďte výraz s „%s“. Príklad:\nhttps://www.google.com/search?q=%s</string>
google.sh:91:res/values-fa/strings.xml:1858:    <string name="search_add_custom_engine_search_string_example" formatted="false">درخواست را با “%s” جایگزین کنید. مثال: \nhttps://www.google.com/search?q=%s</string>
google.sh:92:res/values-ro/strings.xml:1066:    <string name="search_add_custom_engine_search_string_example" formatted="false">Înlocuiește interogarea cu „%s”. Exemplu: \nhttps://www.google.com/search?q=%s</string>
google.sh:93:res/values-tg/strings.xml:1956:    <string name="search_add_custom_engine_search_string_example" formatted="false">Сатри дархостро бо “%s” иваз намоед. Масалан:\nhttps://www.google.com/search?q=%s</string>
google.sh:94:res/values-br/strings.xml:1900:    <string name="search_add_custom_engine_search_string_example" formatted="false">Amsaviñ ar gerioù klasket gant “%s”. Da skouer: \nhttps://www.google.com/search?q= %s</string>
google.sh:95:res/values-bn/strings.xml:970:    <string formatted="false" name="search_add_custom_engine_search_string_example">&quot;%s&quot; দিয়ে কোয়েরি প্রতিস্থাপন করুন। উদাহরণ: \nhttps://www.google.com/search?q=%s</string>
google.sh:96:res/values-tr/strings.xml:1947:    <string name="search_add_custom_engine_search_string_example" formatted="false">Sorguyu “%s” ile değiştirin. Örnek:\nhttps://www.google.com/search?q=%s</string>
google.sh:97:res/values-co/strings.xml:1982:    <string name="search_add_custom_engine_search_string_example" formatted="false">Rimpiazzà i termi di a ricerca da « %s ». Esempiu :\nhttps://www.google.com/search?q=%s</string>
